// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzTQ_I3WWA45zJyDo_WJhL0TgOdkzH0S0',
    appId: '1:447592928913:web:16524652e34715f6a45130',
    messagingSenderId: '447592928913',
    projectId: 'renewable-energy-project-1c67f',
    authDomain: 'renewable-energy-project-1c67f.firebaseapp.com',
    databaseURL: 'https://renewable-energy-project-1c67f-default-rtdb.firebaseio.com',
    storageBucket: 'renewable-energy-project-1c67f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3D7AshRMxa6I9Y9oiFOlM_uBqrr9iuMA',
    appId: '1:447592928913:android:03063d470363aa2ca45130',
    messagingSenderId: '447592928913',
    projectId: 'renewable-energy-project-1c67f',
    databaseURL: 'https://renewable-energy-project-1c67f-default-rtdb.firebaseio.com',
    storageBucket: 'renewable-energy-project-1c67f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQJm9AOWaLr4sezjyR465EAqBqa9O6Lew',
    appId: '1:447592928913:ios:a3745fc6333f961aa45130',
    messagingSenderId: '447592928913',
    projectId: 'renewable-energy-project-1c67f',
    databaseURL: 'https://renewable-energy-project-1c67f-default-rtdb.firebaseio.com',
    storageBucket: 'renewable-energy-project-1c67f.firebasestorage.app',
    iosBundleId: 'com.example.zelestra',
  );
}
